create database customer;
use customer_behavior;
show tables;
select*from customer;
describe customer;

-- que 1>> What is total revenue generated by male vs female customer?
select gender ,sum(purchase_amount) as revenue
from customer
group by gender
order by revenue desc;

-- que 2>> Which customer used discount but still more than tha average purchase amount? 
select  customer_id ,purchase_amount 
from customer  
where discount_applied='Yes' and
purchase_amount >= (select avg(purchase_amount) from customer)
order by purchase_amount desc;

-- que 3>> which are the top 5 product with highest average review rating?
select item_purchased , round(avg(review_rating),2 ) as rating
from  customer
group by item_purchased 
order by rating desc
limit 5; 

-- que 4>> Compare the average purchase amounts between standard and express shipping.
select shipping_type ,round(avg(purchase_amount),2) as amount
from customer 
where shipping_type in ('Standard' ,'Express')
group by shipping_type;

-- Que 5>> Do subscribed customer spend more ? Comapre average spend and total revenue 
-- between subscribe and non subscribers
select subscription_status,count(customer_id)as total_customer ,round(avg(purchase_amount),2) as avg_amount,
round(sum(purchase_amount),2) as total_amount
from customer
group by subscription_status;

-- Que6 >> Which 5 products have highest percentage of puchase with discount applied?
SELECT item_purchased,
ROUND(
SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)
*100.0/COUNT(*),2
) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- que 7 >> Segment customer into new ,returning  and loyal based  on the total  number of perivious  purchase , and show the count  of each segment.
SELECT
CASE
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS total_customers
FROM customer
GROUP BY customer_segment;

-- Que 8>> What are the top 3 most purchased products within each category?
select category, item_purchased ,purchases
from
(
select category,
item_purchased,
count(*) as purchases,
rank() over( partition by category
			order by count(*) desc
           ) as rnk
from customer
group by category, item_purchased) as ranked_products
where rnk <= 3;

-- Que 9 >> Are customers who are repeat buyers(more than 5 previous purchase)also likely  to subscribed?
select subscription_status,
       COUNT(*) as total_customers
from  customer
where previous_purchases > 5
group by subscription_status;

-- Que 10>> What is the revenue contribution of each group ?
select age_group,
       sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;






